version: 2.1

executors:
  default:
    docker:
      - image: quay.io/hemanth22/rockylinux9:9

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Print Python Verson
          command: |
            dnf install python312 python3-pip -y
            python3 -V
            python3 -m pip install requests
            /usr/bin/python3.12 -V
            /usr/bin/python3.12 -m ensurepip
            /usr/bin/python3.12 -m pip install pip --upgrade
            /usr/bin/python3.12 -m pip install -r requirements.txt
      - run:
          name: Read Remainders stored in the database and send remainders
          command: |
            ls -ltr
            /usr/bin/python3.12 telegram_group_snippet/tele_group.py
            /usr/bin/python3.12 postgres_connect/postgres.py
            /usr/bin/python3.12 redisdb_connect/redis_version.py
            /usr/bin/python3.12 postgres_select.py
      - run:
          name: System date
          command: |
            date

workflows:
  notify_app:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "00 3,6,9,12,14,16 * * *"
          filters:
            branches:
              only:
                - main
